---
ID: "8bfb1f44-9d47-42e9-917c-baaa27da21ec"
Parent: "460f2b72-a839-4a13-8a9e-4c75b93ce1a5"
Template: "460f2b72-a839-4a13-8a9e-4c75b93ce1a5"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Content/LegalComplianceBanner/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T131315Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "6c7c427a-4516-40ee-9a91-58961cf2a788"
      Hint: Title
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fd776615-4c63-4984-917e-2cb31d180faf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T131334Z
