---
ID: "fb47b169-832d-43a9-9a82-071e0d6c5037"
Parent: "a16caf37-8ef7-4fb1-a6d4-a85638f4eb15"
Template: "a16caf37-8ef7-4fb1-a6d4-a85638f4eb15"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Forms/NewsletterSignup/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T140845Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "88c36fda-6465-4de4-9ed7-12732b651daa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T140919Z
    - ID: "e2a5eaf9-edc2-464c-9cbb-2635fe5d6af0"
      Hint: PlaceholderText
      Value: Enter your email
    - ID: "e59c4d09-0b59-4053-bbae-a33e36163807"
      Hint: ButtonText
      Value: Subscribe
    - ID: "f6a33cbc-2271-4f11-89d1-fca832a641a4"
      Hint: Title
      Value: $name
