---
ID: "f38bf46f-8a46-456f-b499-9ca3b221176b"
Parent: "31c6bc75-a564-4e78-a887-7c664c3f284b"
Template: "31c6bc75-a564-4e78-a887-7c664c3f284b"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Cards/ProductPricingCards/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{ED669B5F-4392-498E-8F5B-A550F75B8C87}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "93737a97-e387-4e0b-b0a5-de4e5f49868c"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T130309Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "561796b3-766e-4942-b324-ac8228e81aaf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T130323Z
    - ID: "e5346dc2-75c7-4050-8894-e2a6613ec298"
      Hint: Title
      Value: $name
