---
ID: "ca2888a0-91ea-4fb8-9381-899d1ac58907"
Parent: "29792b9c-9b29-4d8f-bf71-02084ee8102a"
Template: "29792b9c-9b29-4d8f-bf71-02084ee8102a"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Social Proof/TestimonialItem/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "14fe8ffd-a7db-46ef-a31f-14309c0d970e"
      Hint: AuthorName
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T132957Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f92e87c4-c5ad-4f2c-ab21-1dd07b053cd9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T133020Z
