---
ID: "039b13a9-ed56-431d-a5a1-c066b2efef04"
Parent: "e9da71e0-f51b-42ce-980d-c959e2a8d427"
Template: "e9da71e0-f51b-42ce-980d-c959e2a8d427"
Path: "/sitecore/templates/Project/fmc-custom-demo/Rendering Parameters/Content/LegalComplianceBanner/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T131653Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "66bbc1d6-dd08-43d2-80af-63ef5186d814"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T131653Z
