---
ID: "f5c726ad-810d-4113-94e2-42b5bec406f5"
Parent: "09a830e9-9170-482d-94a9-b024957c7962"
Template: "09a830e9-9170-482d-94a9-b024957c7962"
Path: "/sitecore/templates/Project/fmc-custom-demo/Rendering Parameters/Cards/ProductPricingCards/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T131105Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3a1b6c7c-d4bd-4e6a-b480-86597c0ae81b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T131105Z
