---
ID: "42662d04-63c7-4f16-9d5f-8a10b158fa4d"
Parent: "e2014bdc-3af2-4add-a731-86e873ebf24c"
Template: "e2014bdc-3af2-4add-a731-86e873ebf24c"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Cards/FeatureCardItem/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T134147Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "134e2b9a-dd93-43b7-b14b-ade08ba263e3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "c0500111-9439-41c0-89e5-d44cf419ef50"
      Hint: CardTitle
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T134213Z
