---
ID: "deb2fe39-e998-4045-adc0-d5ca575bf77a"
Parent: "b2b2ee2c-f290-4e92-bfc8-14cd367e3ea3"
Template: "b2b2ee2c-f290-4e92-bfc8-14cd367e3ea3"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Navigation/TabNavigationSection/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{7F966A80-EA45-48BB-AF11-A9416836739A}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "edce46a1-e87e-4c5e-be22-b23bba83a224"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T122714Z
    - ID: "44e9b658-15ba-436f-9d91-bf07e6e21059"
      Hint: Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3192cc4b-f594-44a0-9c67-6a9051aca646"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T122728Z
