---
ID: "d4d05b7f-4530-4150-b05c-9d5c4dff7456"
Parent: "88376eb8-a0b7-4ffb-aea1-ad143726cfd3"
Template: "88376eb8-a0b7-4ffb-aea1-ad143726cfd3"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Content/TrustStatsRow/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{D7A407DE-322F-432E-8D2C-4F46D11835B1}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "9307653b-6f1e-4461-8288-01d8b57a480b"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T132415Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f2fceaa3-e965-4b55-bbe3-efd753ea753a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "c9f6caf5-6abd-461b-b16c-ac873d4f66b1"
      Hint: Title
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T132438Z
