---
ID: "54fb5f51-c345-40fb-a065-54a62e7ab7e4"
Parent: "d78f8fc7-d951-4771-a3e7-f2709984d4ed"
Template: "d78f8fc7-d951-4771-a3e7-f2709984d4ed"
Path: "/sitecore/templates/Project/fmc-custom-demo/Folders/FeatureCardsGrid Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{E94D3C21-7DE5-4270-B691-8E29673A1E2C}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e9e6459c-3816-4afe-b65e-3db57e2c3c3f"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T134148Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "71679d84-9be9-4a39-8969-29ea9d1a7235"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T134215Z
