---
ID: "38d7a3e0-aec0-4eec-ba2e-a87a4298acb5"
Parent: "73df51e6-e92d-4742-9e0a-74d2ca36ef7f"
Template: "73df51e6-e92d-4742-9e0a-74d2ca36ef7f"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Content/FAQItem/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "216901f9-a9fa-439a-a5b1-3f5651c67540"
      Hint: Question
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T141458Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f811e072-d5ab-4950-9543-c71e2e327a23"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T141523Z
