---
ID: "20d68899-606b-44f9-88c0-c13bad9a38b3"
Parent: "18975833-7fd9-4ca6-a4dc-d01cd3454d4b"
Template: "18975833-7fd9-4ca6-a4dc-d01cd3454d4b"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Content/ValuePropositionItem/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T131840Z
    - ID: "26ad50f0-0c17-4313-b9ca-58fb93ce4b30"
      Hint: ItemTitle
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d25fc4ba-a593-4e60-8766-4371d3cfe282"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T131903Z
