---
ID: "1fd917a8-eb12-4614-ae77-3a667df9cca1"
Parent: "21b5b0d2-34fb-47ff-b995-906ebac653eb"
Template: "21b5b0d2-34fb-47ff-b995-906ebac653eb"
Path: "/sitecore/templates/Project/fmc-custom-demo/Rendering Parameters/Media/ImageGallery/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T140332Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6b42f26a-bbd1-461e-bf9f-356d18ab6f39"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T140332Z
