---
ID: "11d28942-0c79-4041-8eb9-65e1ee1e62bd"
Parent: "bcb19cd2-c0a8-421c-9566-cde9491ee8ae"
Template: "bcb19cd2-c0a8-421c-9566-cde9491ee8ae"
Path: "/sitecore/templates/Project/fmc-custom-demo/Folders/HeroBanner Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{EBB89BFF-86FF-496D-B4F7-57FE722342B6}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "dff76c80-6a40-4fa6-8771-0466c6c3ea06"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260325T121409Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "415ab6d4-5f60-4bc8-b94e-c7572b6a4868"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T121419Z
